services:
  ping:
    container_name: efp-indexer-ping
    image: bash:latest
    build:
        FROM bash:latest
        WORKDIR /usr/src/app
        RUN apk add --no-cache curl && rm -rf /var/cache/apk/*
        COPY ./scripts/ping.sh /usr/src/app/ping.sh
    command: ./ping.sh
    entrypoint: /usr/local/bin/bash
    network_mode: "host"
  anvil:
    container_name: efp-indexer-anvil
    image: ghcr.io/foundry-rs/foundry:latest
    command: anvil
    tty: true
    environment:
      - ANVIL_IP_ADDR=0.0.0.0
    ports:
      - 8545:8545
    network_mode: "host"

  indexer:
    container_name: efp-indexer
    restart: "on-failure:7"
    network_mode: "host"
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    image: efp-indexer:latest
    mem_limit: 10g
    volumes:
      - ./certs:/usr/src/app/certs
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@efp-database:5432/efp?sslmode=disable}
      - DATABASE_SSL_FILE=${DATABASE_SSL_FILE}
      - ENABLE_DATABASE_LOGGING=${ENABLE_DATABASE_LOGGING:-true}
      - CHAIN_ID=${CHAIN_ID:-11155111}
      - ANKR_ID=${ANKR_ID}
      - INFURA_ID=${INFURA_ID}
      - QUIKNODE_PREFIX=${QUIKNODE_PREFIX}
      - QUIKNODE_ID=${QUIKNODE_ID}
      - BASE_SEPOLIA_ALCHEMY_ID=${BASE_SEPOLIA_ALCHEMY_ID}
      - OP_SEPOLIA_ALCHEMY_ID=${OP_SEPOLIA_ALCHEMY_ID}
      - SNITCH_ID=${SNITCH_ID}
      - START_BLOCK=${START_BLOCK}
      - BATCH_SIZE=${BATCH_SIZE}
      - RECOVER_HISTORY=${RECOVER_HISTORY}
      - LLAMAFOLIO_ID=${LLAMAFOLIO_ID}
      - MAINNET_ALCHEMY_ID=${MAINNET_ALCHEMY_ID}
      - SEPOLIA_ALCHEMY_ID=${SEPOLIA_ALCHEMY_ID}
      - OPTIMISM_ALCHEMY_ID=${OPTIMISM_ALCHEMY_ID}
      - ETHEREUM_LOCAL_NODE_URL=${ETHEREUM_LOCAL_NODE_URL:-http://host.docker.internal:8545}
      - ANVIL_ACCOUNT_PRIVATE_KEY=${ANVIL_ACCOUNT_PRIVATE_KEY:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}
      - EFP_CONTRACT_ACCOUNT_METADATA=${EFP_CONTRACT_ACCOUNT_METADATA:-0x16a3457dB1D7dc58196C0b94D8F49f5e9eCba611}
      - EFP_CONTRACT_LIST_REGISTRY=${EFP_CONTRACT_LIST_REGISTRY:-0xd66c005A5F1e26BaaDe97cb9f270c9Edfa78a684}
      - EFP_CONTRACT_LIST_RECORDS=${EFP_CONTRACT_LIST_RECORDS:-0x84340faBF70340153fAB988404C4356EEf14d581}
      - EFP_CONTRACT_LINT_MINTER=${EFP_CONTRACT_LINT_MINTER:-0x8581B0CA827Cf577269721A596CEfC2ffc09BaDB}
      - EFP_CONTRACT_LIST_MINTER=${EFP_CONTRACT_LIST_MINTER:-0x8581B0CA827Cf577269721A596CEfC2ffc09BaDB}